# Generated by Django 3.2.9 on 2021-11-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecrudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='speed',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
