# Generated by Django 3.2.9 on 2021-11-23 07:39

from django.db import migrations, models
import vehiclecrudapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecrudapp', '0002_vehicle_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vehiclecrudapp.models.filepath),
        ),
    ]
